import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { NavBar } from "@/components/nav/nav";
import { FooterSection } from "@/components/footer/footerSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
